export const ActionTypes = {
    DEPOSITAR: "DEPOSITAR",
    RETIRAR: "RETIRAR",
    SET_POKEMONS: "SET_POKEMONS",
    SELECTED_POKEMON: "SELECTED_POKEMON",
    UPDATED_POKEMON: "UPDATED_POKEMON",
    REMOVED_POKEMON: "REMOVED_POKEMON",
    ADD_POKEMON: "ADD_POKEMON",
}